services:
  springboot-api:
    build:
      context: . 
    container_name: springboot-api
    image: arbitros-springboot:latest
    ports:
      - "8080:8080"    
    environment:
      - JAVA_OPTS=-Xms512m -Xmx512m   
    networks:
      - arbitros-net

networks:
  arbitros-net:
    driver: bridge